name: update-fork

on:
  workflow_dispatch:
  push:
    branches:
      - fork

concurrency:
  group: update-fork
  cancel-in-progress: false
    
jobs:        
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      
      - env:
          PAT_FOR_MW: ${{ secrets.PAT_FOR_MW }}
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile
          pnpm build

          git clone https://$PAT_FOR_MW@github.com/goofw/mw
          cd mw
          mkdir -p mwp/lib
          cp ../package.json mwp
          cp ../lib/index.js mwp/lib

          git config user.name $(git log -1 --pretty=format:'%an')
          git config user.email $(git log -1 --pretty=format:'%ae')
          git add .
          git diff-index --quiet HEAD || git commit -m "update"
          git push
